name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH agent
      run: eval "$(ssh-agent -s)"
    
    - name: Add SSH private key
      run: ssh-add ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/directus_wanesni
          git pull origin main
          git status
          npm install
          pm2 restart all
